In [24]:
import pandas as pd
import numpy as np

In [25]:
#GPT-5 Code to make a linearly seperable dataset (x1 + 2x2 = -0.25)
rng = np.random.default_rng(0)
n = 300
X = rng.uniform(-1, 1, size=(n, 2))
y = np.where(X[:, 0] + (2*X[:, 1]) > -0.25, 1, -1)

df = pd.DataFrame({"x1": X[:, 0], "x2": X[:, 1], "y": y})
df.head(), len(df)

(         x1        x2  y
 0  0.273923 -0.460427 -1
 1 -0.918053 -0.966945 -1
 2  0.626540  0.825511  1
 3  0.213272  0.458993  1
 4  0.087250  0.870145  1,
 300)

In [ ]:
#Perceptron
w1 = 0
w2 = 0
bias = 0
n = 1000 #Perceptron iterations; should be infinite

for i in range(n):
    mistakes = 0
    for j in range(len(df)):
        x1 = df.iloc[j]['x1']
        x2 = df.iloc[j]['x2']
        y = df.iloc[j]['y']
        if y * ((w1 * x1) + (w2 * x2) + bias) <= 0:
            w1 += y * x1
            w2 += y * x2
            bias += y
            mistakes += 1
    if mistakes == 0:
        break

print(f"Total iterations: {i}")
print(f"Number of mistakes: {mistakes}")
print(f"Final weights: w1 = {w1}, w2 = {w2}, bias = {bias}")

Total iterations: 48
Number of mistakes: 0
Final weights: w1 = 8.157878209309867, w2 = 16.065704995274753, bias = 2.0


In [ ]:
X = np.array([[-1,-1], [-1,1], [1,-1], [1,1]], dtype=float)
y = np.array([-1, 1, 1, -1], dtype=int)

#X0 * X1 gives positive value for the same sign and negative for different signs
Z = np.column_stack([X, X[:,0]*X[:,1]])
print(Z)

# Perceptron in feature space
w = np.zeros(Z.shape[1])
b = 0.0
for _ in range(100):
    mistakes = 0
    for i in range(len(Z)):
        if y[i] * (Z[i] @ w + b) <= 0:
            w += y[i] * Z[i]
            b += y[i]
            mistakes += 1
    if mistakes == 0:
        break

pred = np.where(Z @ w + b > 0, 1, -1)
print("accuracy:", (pred == y).mean(), "final weights:", w, "bias:", b)

[[-1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1. -1.]
 [ 1.  1.  1.]]
accuracy: 1.0 final weights: [ 0.  0. -4.] bias: 0.0
